[package]
name = "fancy_sort"
version = "0.1.0"
edition = "2021"
authors = ["Bastian Asmussen <bastianasmussen@gmail.com>"]
license-file = "LICENSE"
readme = "README.md"
description = "Implementations of different sorting algorithms in Rust!"

[dependencies]
rand = "0.8.5"
